---
#
# Tasks and roles for all hosts
#
- hosts: fleet
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml
        tags:
            - always
            - port

- hosts: fleet
  become: yes

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system

      - role: neovim
        tags:
            - neovim

      - role: geerlingguy.security
        # No Archlinux support upstream
        when: ansible_os_family != "Archlinux"
        tags:
            - security

      - role: geerlingguy.docker
        tags:
            - docker

      - role: geerlingguy.ntp
        tags:
            - ntp

      - role: chriswayg.msmtp-mailer
        # Debian/Ubuntu only upstream - no Fedora or Arch support
        when: ansible_os_family == "Debian"
        tags:
            - msmtp

      - name: containers
        tags:
          - containers

      - role: tailscale
        when: tailscale_enabled | default(false)
        tags:
            - tailscale

      - role: netbird
        when: netbird_enabled | default(false)
        tags:
            - netbird

  post_tasks:
      - import_tasks: tasks/redhat_ssh_firewall.yml
        when:
            - ansible_os_family == "RedHat"
            - security_ssh_port is defined
        tags:
            - security
