{% set lan_interface = (networks | selectattr('name', '==', 'lan') | map(attribute='interface') | first) %}
{% set app_base = (networks | selectattr('name', '==', 'app') | map(attribute='base') | first) %}
network:
  version: 2
  ethernets:
    {{ lan_interface }}:
      dhcp4: true
  vlans:
    app:
      id: 4
      link: {{ lan_interface }}
      addresses: [ '{{ app_base }}.228/24' ]
