---
- include_vars: "vars/{{ ansible_os_family }}.yml"
- include_tasks: netplan.yml
- include_tasks: essential.yml
- include_tasks: user.yml
- include_tasks: dotfiles.yml
  tags:
      - dotfiles

- include_tasks: workstation.yml
  when: workstation_mode | default(false)
  tags:
      - workstation
