- name: Add netbird dnf repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/netbird.repo
    mode: "0644"
    content: |
      [netbird]
      name=netbird
      baseurl=https://pkgs.netbird.io/yum/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.netbird.io/yum/repodata/repomd.xml.key
      repo_gpgcheck=1

- name: Install netbird
  ansible.builtin.dnf:
    name: netbird
    update_cache: yes
    state: present
